base class members marked with abstract keyboard
require that derived classes override them
compiler error CS0534: does not implement inherited abstract member
class B provides no implementation for A.Method1